version: "3.8"
services:
    train:
        container_name: "yolov5-train"
        build: "./train"
        shm_size: '2gb'
        command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        env_file:
            - ".env"
        environment:
            - RESPONSE_URL=http://127.0.0.1:8000/response
            - LOGGER_URL=http://127.0.0.1:8000/logger
            - IS_LOGGER_ON=False
        ports:
            - '8000:8000'
        volumes:
            - ./train:/code
            - ./volumes/weights:/weights
            - ./volumes/dataset/images:/dataset/images
            - ./volumes/dataset/labels:/dataset/labels
        ipc: host
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
